version: "3.7"
services:
  docker-tutorial:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: docker-tutorial
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: docker
      DB_USERNAME: docker
      DB_PASSWORD: docker
  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker